# This workflow merges all HCL reports into a single file to be used at https://www.qubes-os.org/hcl/

name: Build

on:
  push:
    branches:
    - master
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Merge all reports
        run: cat *.yml > full-list.yml
      
      - name: Lint
        run: echo "TODO Linting"
        
      - name: Upload the full-list.yml artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: full-list.yml
          path: full-list.yml
        if-no-files-found: error
        retention-days: 0
